version: v1

server:
  port: 8083
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 12345678
    key-alias: listener
    enabled: true
  error:
    include-message: always

openExchangeRates:
  url: https://openexchangerates.org/api
  latest: /latest.json
  historical: /historical
  appId: [OpenExchangeRates API token]
  baseCurrency: USD

giphy:
  url: https://api.giphy.com/v1/gifs/random
  apiKey: [Giphy API token]
  upTag: rich
  downTag: broke
  rating: g
